# 이 build.yaml 파일은 MW60A 키보드 펌웨어의 일부임
---
 include:
   - board: nice_nano_v2
     shield: mw60a

#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: corne_left
     snippet: studio-rpc-usb-uart
     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
